### ISSUE TITLE
'class WiFiManager' has no member named 'getStaticMode'

### ISSUE THREAD

**Issue by gbourlier** [ElToberino/Tobers_Multidisplay#1]
Hi
Great job.
But i can't compile 👍 C:\Users\bourl\Downloads\multidisplay_1.1_EN\multidisplay_1.1_EN\multidisplay_1.1_EN.ino: In function 'void wificonnect()':

multidisplay_1.1_EN:823:25: error: 'class WiFiManager' has no member named 'getStaticMode'

         if (wifiManager.getStaticMode() == true) {                            // gets information from WiFiManager if connection has been made with static IP

                         ^

Plusieurs bibliothèque trouvées pour "WiFiManager.h"
Utilisé : C:\Users\bourl\OneDrive\Documents\Arduino\libraries\WiFiManager-master
Non utilisé : C:\Users\bourl\OneDrive\Documents\Arduino\libraries\WiFiManager_for_Multidisplay-development
Plusieurs bibliothèque trouvées pour "WiFiClient.h"
Utilisé : C:\Users\bourl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi
Non utilisé : C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'class WiFiManager' has no member named 'getStaticMode'

If you can help me

**Comment by victor7376** [comment]
You’ve got to download his modified version of the WiFi manager

https://github.com/ElToberino/WiFiManager_for_Multidisplay

**Comment by ElToberino** [comment]
Sorry for the late answer.
Yes, you need my own version of WifiManger - and this is important: You can't have both WifiManager Versions in your libraries directory!
This error message describes your problem: "Plusieurs bibliothèque trouvées pour "WiFiManager.h"
Close Arduino IDE, move the normal WifiManager out of your library folder and restart Ardunio IDE - then the compiling should work fine.
Best regards!
