### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by victor7376** [ElToberino/Tobers_Multidisplay#2]
Not really an issue, more of a comment.

Trying to read the code within this can give you a headache lol.

But I do love all the different modes for scrolling etc and having the Spotify feature.

Have you thought about laying out the code within different cpp & h formats?

For example (This is for the ESP8266):
https://github.com/Qrome/marquee-scroller/tree/master/marquee

**Comment by ElToberino** [comment]
Thanks for your suggestion.
I know the amount of code is really large. But that shows how my project has developed: In the beginning, I just wanted to create my own news and weather display; but then I added more and more features and that's where we are today...

I tried to write the code as clearly arranged as possible and I also added a lot of comments and explanations, links, hints etc. 
So I think it should be possible to understand/retrace it. I actually don't plan to change the structure of my code, but I'll try to keep it up to date.
Best regards!
