### ISSUE TITLE
Wetteranzeige Web Interface

### ISSUE THREAD

**Issue by obkram** [ElToberino/Tobers_Multidisplay#4]
Hallo lieber Entwickler, Ihr projekt macht viel Spaß. Vielen Dank dafür.
Ich habe in der multidisplay_1.3_DE die Wetterdaten und den API Key entsprechend angepasst. Auf dem Display werden die Wetterdaten korrekt angezeigt, aber über die Wetteranzeige im Webinterface bekomme ich immer noch ( nur ) Wien und Innsbruck angezeigt. Wo sind die Daten denn noch hinterlegt?

**Comment by ElToberino** [comment]
Danke für die Rückmeldung. Freut mich, dass es Ihnen gefällt!

Es ist im Artikel auf hackster.io auch beschrieben: 
Die Wetter-Html-Seite verwendet aus verschiedenen Gründen keine Widgets von openweather, kann sich daher auch nicht automatisch den im Code hinterlegten Ortsdaten anpassen. Diese Anpassung muss vielmehr manuell im Html-Code der Seite weather.html angepasst werden - es ist der Code in den beiden Iframes.
Also einfach auf wetteronline.de gehen, das [Widget erstellen](https://www.wetteronline.de/wetter-widget) und dann in die weather.html einfügen. Anschließend weather.html über die Spiffs-Verwaltung neu hochladen.

**Comment by obkram** [comment]
Vielen Dank für die schnelle und ausführliche Antwort. Die Links werden sicherlich sehr hilfreich sein. Ich denke mit dieser Anleitung sollte sogar ich das hinbekommen.

Danke und Gruß Sven

**Comment by obkram** [comment]
@ElToberino 👍 Es hat funktioniert. War spielend einfach mit Ihrer Anleitung. Danke nochmal.
