### ISSUE TITLE
User Message in Custom Font

### ISSUE THREAD

**Issue by CCERocks** [ElToberino/Tobers_Multidisplay#5]
Hi.. i wonder how hard to put custom font ie Arabic Font into the code? 

id try to paste the Arabic Font Character into the user message but didnt show up.

**Comment by ElToberino** [comment]
> id try to paste the Arabic Font Character into the user message but didnt show up.

Of course this cannot work without choosing the arabic font of the Parola Library. Please take a look at [this example](https://github.com/MajicDesigns/MD_Parola/tree/main/examples/Parola_Fonts) and change the code according to that.
There is also [a nice font editor](https://pjrp.github.io/MDParolaFontEditor) available which simplifies creating/changing fonts.

I would recommend to run the example program linked above until you've found the right font setup according to your needs. After that it will be really simple to modify the multidisplay code.
